/**
 * Interface representing the output of a child process execution.
 * This provides a generic structure for capturing both standard output (stdout) and standard error (stderr) streams.
 *
 * @interface ProcessOutput
 * @property {string} stdout - The standard output (stdout) generated by the child process.
 * @property {string} stderr - The standard error (stderr) generated by the child process.
 *
 */
export interface ProcessOutput {
	stdout: string;
	stderr: string;
}
